language: cpp

git:
  quiet: true

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libboost-all-dev
      env: COMPILER=g++-6

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libboost-all-dev
      env: COMPILER=g++-7

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libboost-all-dev
      env: COMPILER=g++-8

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libboost-all-dev
            - g++-7
      env: COMPILER=clang++-5.0

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - libboost-all-dev
            - g++-7
      env: COMPILER=clang++-6.0

before_script:
  - export ROOT_FOLDER="$(pwd)"
  - export BUILD_FOLDER="$(pwd)/src"
  - cd ${BUILD_FOLDER}
  - export CXX=${COMPILER}
  - ${CXX} --version

script:
  - CHANGED_FILES=`git diff --name-only master ${TRAVIS_COMMIT}`
  # Check build without libosrm only if source files have been
  # modified.
  - if echo ${CHANGED_FILES} | grep -v -e "\.h" -e "\.cpp"; then travis_terminate 0; fi
  - make
  # Check build with libosrm installed only on master and if relevant
  # files have been modified.
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ] && echo ${CHANGED_FILES} | grep -v "libosrm_wrapper"; then travis_terminate 0; fi
  - make clean
  - cd ${ROOT_FOLDER}
  - sudo apt-get install build-essential wget cmake3 pkg-config libbz2-dev libstxxl-dev libstxxl1 libxml2-dev libzip-dev lua5.2 liblua5.2-dev libtbb-dev
  - git clone https://github.com/Project-OSRM/osrm-backend.git
  - cd osrm-backend
  - git checkout v5.19.0
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
  - sudo cmake --build . --target install
  - cd ${BUILD_FOLDER}
  - make
